// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperheroApi.Models;

#nullable disable

namespace SuperheroApi.Migrations
{
   [DbContext(typeof(SuperHeroContext))]
   [Migration("20240128010400_AddSuperHerosTable")]
   partial class AddSuperHerosTable
   {
      /// <inheritdoc />
      protected override void BuildTargetModel(ModelBuilder modelBuilder)
      {
#pragma warning disable 612, 618
         modelBuilder
             .HasAnnotation("ProductVersion", "8.0.1")
             .HasAnnotation("Relational:MaxIdentifierLength", 128);

         SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

         modelBuilder.Entity("SuperHero", b =>
             {
                b.Property<string>("Id")
                       .HasColumnType("nvarchar(450)");

                b.Property<string>("Name")
                       .IsRequired()
                       .HasColumnType("nvarchar(max)");

                b.Property<string>("Superpowers")
                       .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("SuperHeroes");
             });
#pragma warning restore 612, 618
      }
   }
}
